-- THT golfapp – schema v1 (2026-10-07)
-- Standard-Postgres så långt det går (lätt att flytta från Supabase).
-- Id:n från gamla MySQL-databasen behålls vid migrering (BID, PID, DID, THTnr).
-- Härledda värden (poäng, eagle/birdie, hålvinster) lagras INTE – se vyerna i 02_vyer.sql.

-- ============ Grunddata ============

create table tht (
  nr        int primary key,                 -- THT-nummer (gamla THTnr)
  artal     int not null unique,
  ort       text not null,
  kronika   text
);

create table person (
  id        int generated by default as identity primary key,   -- gamla PID
  fornamn   text not null,
  efternamn text not null,
  hcp       numeric(3,1),                     -- aktuellt handicap, uppdateras manuellt
  aktiv     boolean not null default true
);

-- Personuppgifter som bara admin ska se (N-22). Inga policies = ingen åtkomst via appen.
create table person_kontakt (
  person_id int primary key references person(id) on delete cascade,
  golf_id   text,
  adress    text,
  epost     text,
  telefon   text
);

-- ============ Banor ============

create table bana (
  id          int generated by default as identity primary key,  -- gamla BID
  namn        text not null,
  slope       numeric(5,2),
  restaurang  boolean not null default false,
  rattigheter boolean not null default false,
  lat         double precision,               -- WGS84
  lon         double precision,
  osm_id      bigint                          -- golfbanans id i OpenStreetMap (om känt)
);

-- En ny version när banan byggts om (F-55). Gamla resultat pekar på den version som gällde.
create table banversion (
  id           int generated by default as identity primary key,
  bana_id      int not null references bana(id) on delete cascade,
  giltig_fran  date not null,
  kommentar    text,
  unique (bana_id, giltig_fran)
);

create table hal (
  id            int generated by default as identity primary key,
  banversion_id int not null references banversion(id) on delete cascade,
  nr            smallint not null check (nr between 1 and 18),
  par           smallint not null check (par between 3 and 6),
  hcp_index     smallint not null check (hcp_index between 1 and 18),
  unique (banversion_id, nr)
);

create table tee (
  id            int generated by default as identity primary key,
  banversion_id int not null references banversion(id) on delete cascade,
  namn          text not null,               -- t.ex. gul, röd, 57
  slope         numeric(5,1),
  course_rating numeric(4,1),
  unique (banversion_id, namn)
);

create table hal_langd (
  hal_id  int not null references hal(id) on delete cascade,
  tee_id  int not null references tee(id) on delete cascade,
  langd   smallint not null check (langd > 0),  -- meter
  primary key (hal_id, tee_id)
);

-- ============ Tävling ============

create table deltavling (
  id            int generated by default as identity primary key,  -- gamla DID
  tht_nr        int not null references tht(nr),
  banversion_id int not null references banversion(id),
  tee_id        int references tee(id),          -- standard-tee för deltävlingen
  ordning       smallint not null,               -- runda 1, 2, 3 under THT (gamla ArsRondIndex)
  namn          text not null,
  datum         date not null,
  narmast_hal   smallint check (narmast_hal between 1 and 18),
  longest_hal   smallint check (longest_hal between 1 and 18),
  unique (tht_nr, ordning)
);

create table runda (
  id            int generated by default as identity primary key,
  deltavling_id int not null references deltavling(id) on delete cascade,
  person_id     int not null references person(id),
  spel_hcp      smallint not null,               -- en gång per runda (F-05)
  boll_nr       smallint,
  tee_id        int references tee(id),          -- om spelaren går från annan tee än standard
  kommentar     text,
  last          boolean not null default false,  -- låst mot ändringar (F-12)
  unique (deltavling_id, person_id)
);

-- Slag per hål. Tak par + 5 (F-06b) tillämpas i vyerna, så verkligt antal kan sparas.
create table score (
  runda_id   int not null references runda(id) on delete cascade,
  hal_nr     smallint not null check (hal_nr between 1 and 18),
  slag       smallint check (slag between 1 and 20),   -- null = ej registrerat
  puttar     smallint check (puttar between 0 and 10), -- null = ej registrerat (saknas första åren)
  andrad     timestamptz not null default now(),
  primary key (runda_id, hal_nr)
);

create table pris (
  deltavling_id int not null references deltavling(id) on delete cascade,
  typ           text not null check (typ in ('narmast', 'longest')),
  person_id     int not null references person(id),
  primary key (deltavling_id, typ)
);

create table ban_betyg (
  tht_nr    int not null references tht(nr),
  bana_id   int not null references bana(id),
  person_id int not null references person(id),
  betyg     numeric(3,1) not null,
  primary key (tht_nr, bana_id, person_id)
);

create table overnattning (
  id           int generated by default as identity primary key,
  tht_nr       int not null references tht(nr),
  platsnamn    text not null,
  antal_natter smallint,
  organisator  text,
  lat          double precision,
  lon          double precision
);

create index on banversion (bana_id);
create index on hal (banversion_id);
create index on deltavling (banversion_id);
create index on runda (person_id);
create index on pris (person_id);
create index on ban_betyg (bana_id);
create index on ban_betyg (person_id);
create index on overnattning (tht_nr);

-- uppdatera "andrad" automatiskt
create function satt_andrad() returns trigger language plpgsql set search_path = '' as $$
begin new.andrad := now(); return new; end $$;
create trigger score_andrad before update on score for each row execute function satt_andrad();

-- ============ Behörighet (Row Level Security) ============
-- Läsa: alla (statistik är öppen). Skriva: inloggad (gemensam kod = ett delat konto, N-20).
-- person_kontakt: RLS på men inga policies => bara admin via Supabase-panelen.

do $$
declare t text;
begin
  foreach t in array array['tht','person','bana','banversion','hal','tee','hal_langd',
                           'deltavling','runda','score','pris','ban_betyg','overnattning'] loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy "alla kan läsa" on %I for select to anon, authenticated using (true)', t);
    execute format('create policy "inloggad kan skriva" on %I for insert to authenticated with check (true)', t);
    execute format('create policy "inloggad kan ändra" on %I for update to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- Radera bara resultat (inte grunddata) från appen
create policy "inloggad kan radera" on score for delete to authenticated using (true);
create policy "inloggad kan radera" on runda for delete to authenticated using (true);
create policy "inloggad kan radera" on pris  for delete to authenticated using (true);

alter table person_kontakt enable row level security;
